import torch
import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm
import numpy as np


# Define the Generator model
class Generator(nn.Module):
    def __init__(self, input_size, output_size):
        super(Generator, self).__init__()
        self.fc1 = nn.Linear(input_size, 64)
        self.fc2 = nn.Linear(64, 128)
        self.fc3 = nn.Linear(128, output_size)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)  # Generate next timestep
        return x


# Define the Discriminator model
class Discriminator(nn.Module):
    def __init__(self, input_size):
        super(Discriminator, self).__init__()
        self.fc1 = nn.Linear(input_size, 128)
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 1)

    def forward(self, real, fake):
        x = torch.cat([real, fake], dim=1)  # Concatenate real and predicted next timestep
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))  # Output a probability of real or fake
        return x


# Define the GAN model
class GAN(nn.Module):
    def __init__(self, generator, discriminator):
        super(GAN, self).__init__()
        self.generator = generator
        self.discriminator = discriminator

    def forward(self, real):
        fake = self.generator(real)  # Generate fake next timestep
        validity = self.discriminator(real, fake)  # Check if the fake is real
        return fake, validity


    # Training function
    def do_train(self, data, source_ts, target_ts, epochs=200, batch_size=64, lr=0.0002):
        criterion = nn.BCELoss()
        optimizer_G = optim.Adam(self.generator.parameters(), lr=lr, betas=(0.5, 0.999))
        optimizer_D = optim.Adam(self.discriminator.parameters(), lr=lr, betas=(0.5, 0.999))

        half_batch = batch_size // 2
        for epoch in range(epochs):
            # Train discriminator with real data
            idx = np.random.randint(0, data.shape[0], half_batch)
            real_data = torch.tensor(data[idx], dtype=torch.float32)
            real_labels = torch.ones((half_batch, 1))  # Real labels = 1

            # Train discriminator with fake data generated by the generator
            noise = real_data  # The generator takes real data as input to predict the next timestep
            fake_data = self.generator(noise)
            fake_labels = torch.zeros((half_batch, 1))  # Fake labels = 0

            # Train discriminator to classify real and fake data
            optimizer_D.zero_grad()

            # Loss for real data
            real_loss = criterion(self.discriminator(real_data, real_data), real_labels)

            # Loss for fake data
            fake_loss = criterion(self.discriminator(real_data, fake_data.detach()), fake_labels)

            # Backprop and optimize
            d_loss = (real_loss + fake_loss) / 2
            d_loss.backward()
            optimizer_D.step()

            # Train generator (via the GAN model, which has the discriminator frozen)
            optimizer_G.zero_grad()

            # We want the generator to fool the discriminator, so we use real labels here
            g_loss = criterion(self.discriminator(real_data, fake_data), real_labels)
            g_loss.backward()
            optimizer_G.step()

            if epoch % 50 == 0:
                print(f"Epoch {epoch} | Discriminator Loss: {d_loss.item()} | Generator Loss: {g_loss.item()}")
        # last epoch
        print(f"Epoch {epoch} | Discriminator Loss: {d_loss.item()} | Generator Loss: {g_loss.item()}")

        torch.save(self, f'gan_{source_ts}_{target_ts}')

